//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <WHILE>
 * f1 -> <PAR_IZQ>
 * f2 -> ExpresionCondicional()
 * f3 -> <PAR_DER>
 * f4 -> <CUR_IZQ>
 * f5 -> ( Sentencia() )+
 * f6 -> <CUR_DER>
 */
public class SentenciaWhile implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public ExpresionCondicional f2;
   public NodeToken f3;
   public NodeToken f4;
   public NodeList f5;
   public NodeToken f6;

   public SentenciaWhile(NodeToken n0, NodeToken n1, ExpresionCondicional n2, NodeToken n3, NodeToken n4, NodeList n5, NodeToken n6) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
   }

   public SentenciaWhile(NodeToken n0, ExpresionCondicional n1, NodeToken n2, NodeToken n3, NodeList n4, NodeToken n5) {
      f0 = new NodeToken("while");
      f1 = n0;
      f2 = n1;
      f3 = n2;
      f4 = n3;
      f5 = n4;
      f6 = n5;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

