//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> DeclararVariable() <PUNTO_COMA>
 *       | SentenciaLeer() <PUNTO_COMA>
 *       | SentenciaImprimir() <PUNTO_COMA>
 *       | AsignarValor() <PUNTO_COMA>
 *       | SentenciaIf()
 *       | SentenciaFor()
 *       | SentenciaWhile()
 */
public class Sentencia implements Node {
   public NodeChoice f0;

   public Sentencia(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

