//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <IMPRIMIR>
 * f1 -> <PAR_IZQ>
 * f2 -> Expresion()
 * f3 -> <PAR_DER>
 */
public class SentenciaImprimir implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Expresion f2;
   public NodeToken f3;

   public SentenciaImprimir(NodeToken n0, NodeToken n1, Expresion n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public SentenciaImprimir(NodeToken n0, Expresion n1, NodeToken n2) {
      f0 = new NodeToken("writeln");
      f1 = n0;
      f2 = n1;
      f3 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

