//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors must implement this interface.
 */

public interface GJVisitor<R,A> {

   //
   // GJ Auto class visitors
   //

   public R visit(NodeList n, A argu);
   public R visit(NodeListOptional n, A argu);
   public R visit(NodeOptional n, A argu);
   public R visit(NodeSequence n, A argu);
   public R visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( Sentencia() )+
    */
   public R visit(Programa n, A argu);

   /**
    * f0 -> DeclararVariable() <PUNTO_COMA>
    *       | SentenciaLeer() <PUNTO_COMA>
    *       | SentenciaImprimir() <PUNTO_COMA>
    *       | AsignarValor() <PUNTO_COMA>
    *       | SentenciaIf()
    *       | SentenciaFor()
    *       | SentenciaWhile()
    */
   public R visit(Sentencia n, A argu);

   /**
    * f0 -> TipoDato()
    * f1 -> <VARIABLE>
    */
   public R visit(DeclararVariable n, A argu);

   /**
    * f0 -> <ENTERO>
    *       | <FLOTANTE>
    *       | <STRING>
    */
   public R visit(TipoDato n, A argu);

   /**
    * f0 -> <LECTURA>
    * f1 -> <PAR_IZQ>
    * f2 -> <VARIABLE>
    * f3 -> <PAR_DER>
    */
   public R visit(SentenciaLeer n, A argu);

   /**
    * f0 -> <IMPRIMIR>
    * f1 -> <PAR_IZQ>
    * f2 -> Expresion()
    * f3 -> <PAR_DER>
    */
   public R visit(SentenciaImprimir n, A argu);

   /**
    * f0 -> <VARIABLE>
    * f1 -> <ASIGNACION>
    * f2 -> Expresion()
    */
   public R visit(AsignarValor n, A argu);

   /**
    * f0 -> ExpresionSimple()
    * f1 -> ( OperadorComparacion() ExpresionSimple() )?
    */
   public R visit(Expresion n, A argu);

   /**
    * f0 -> <COMPARACION>
    *       | <MENOR_QUE>
    *       | <MAYOR_QUE>
    *       | <MENOR_IGUAL>
    *       | <MAYOR_IGUAL>
    */
   public R visit(OperadorComparacion n, A argu);

   /**
    * f0 -> Termino()
    * f1 -> ( OperadorTermino() Termino() )*
    */
   public R visit(ExpresionSimple n, A argu);

   /**
    * f0 -> <SUMA>
    *       | <RESTA>
    */
   public R visit(OperadorTermino n, A argu);

   /**
    * f0 -> Factor()
    * f1 -> ( OperadorFactor() Factor() )*
    */
   public R visit(Termino n, A argu);

   /**
    * f0 -> <MULTIPLICACION>
    *       | <DIVISION>
    *       | <MODULO>
    */
   public R visit(OperadorFactor n, A argu);

   /**
    * f0 -> Complejo()
    * f1 -> ( OperadorComplejo() Complejo() )*
    */
   public R visit(Factor n, A argu);

   /**
    * f0 -> <POTENCIA>
    *       | <RAIZ_CUADRADA>
    */
   public R visit(OperadorComplejo n, A argu);

   /**
    * f0 -> <PAR_IZQ> Expresion() <PAR_DER>
    *       | Valor()
    *       | <VARIABLE>
    */
   public R visit(Complejo n, A argu);

   /**
    * f0 -> <NUM_ENTERO>
    *       | <NUM_FLOTANTE>
    *       | <CADENA>
    */
   public R visit(Valor n, A argu);

   /**
    * f0 -> <AND>
    *       | <OR>
    *       | <NOT>
    */
   public R visit(OperadorLogico n, A argu);

   /**
    * f0 -> <IF>
    * f1 -> <PAR_IZQ>
    * f2 -> ExpresionCondicional()
    * f3 -> <PAR_DER>
    * f4 -> <CUR_IZQ>
    * f5 -> ( Sentencia() )+
    * f6 -> <CUR_DER>
    * f7 -> ( ExpresionElse() )?
    */
   public R visit(SentenciaIf n, A argu);

   /**
    * f0 -> <ELSE>
    * f1 -> <CUR_IZQ>
    * f2 -> ( Sentencia() )+
    * f3 -> <CUR_DER>
    */
   public R visit(ExpresionElse n, A argu);

   /**
    * f0 -> Expresion()
    * f1 -> ( OperadorLogico() Expresion() )*
    */
   public R visit(ExpresionCondicional n, A argu);

   /**
    * f0 -> <FOR>
    * f1 -> <PAR_IZQ>
    * f2 -> <ENTERO>
    * f3 -> <VARIABLE>
    * f4 -> <ASIGNACION>
    * f5 -> <NUM_ENTERO>
    * f6 -> <PUNTO_COMA>
    * f7 -> <VARIABLE>
    * f8 -> OperadorComparacion()
    * f9 -> <NUM_ENTERO>
    * f10 -> <PUNTO_COMA>
    * f11 -> <VARIABLE>
    * f12 -> OperadorAumento()
    * f13 -> <PAR_DER>
    * f14 -> <CUR_IZQ>
    * f15 -> ( Sentencia() )+
    * f16 -> <CUR_DER>
    */
   public R visit(SentenciaFor n, A argu);

   /**
    * f0 -> "++"
    *       | "--"
    */
   public R visit(OperadorAumento n, A argu);

   /**
    * f0 -> <WHILE>
    * f1 -> <PAR_IZQ>
    * f2 -> ExpresionCondicional()
    * f3 -> <PAR_DER>
    * f4 -> <CUR_IZQ>
    * f5 -> ( Sentencia() )+
    * f6 -> <CUR_DER>
    */
   public R visit(SentenciaWhile n, A argu);

}
